### ISSUE TITLE
Cannot use get_ functions with subsetted or filtered act_data

### ISSUE THREAD

**Issue by baslat** [fawda123/rStrava#47]
I am unable to use `get_elev_prof` or `get_heat_map` on subseted or filtered `act_data`.

If I use `filter`, a data frame is returned and that's not a valid class for the `get_` functions. If I use `subset`, the class is valid but I get units errors (all my activities are in metric units.). Code is below.

```
mykey <- Sys.getenv("google_key")
stoken <- httr::config(token = readRDS('.httr-oauth')[[1]])
my_acts <- get_activity_list(stoken)

# use subset to find runs with 'spartan' in the name
spartans_subs <- compile_activities(my_acts, units = "metric") %>%
  subset(grepl('Spartan', name))

# use filter to find runs with 'spartan' in the name
spartans_filt <- compile_activities(my_acts, units = "metric") %>%
  filter(grepl('Spartan', name))

# pick a known activity with spartan in the name for testing
act_data <- compile_activities(my_acts, units = "metric")
spartans_test <- act_data[406,]  #same activity as spartans_subs[3, ] and spartan_filt[3, ]

# what are the classes and dimensions of the selected data
class(spartans_subs)
[1] "actframe"   "data.frame"
dim(spartans_subs)
[1]  6 60

class(spartans_filt)
[1] "data.frame"
dim(spartans_filt)
[1]  6 60

class(spartan_test)
[1] "actframe"   "data.frame"
dim(spartan_test)
[1]  1 60

## try to get maps and elevation profiles
#use subsetted data
get_heat_map(spartans_subs, acts = 3, key = mykey, source = "osm")
Error in if (unit_type %in% "imperial") temp$distance <- temp$distance *  : 
  argument is of length zero

get_elev_prof(spartans_subs, acts = 3, key = mykey)
Error in if (unit_type %in% "imperial") { : argument is of length zero

#use fitlered data
get_heat_map(spartans_filt, acts = 3, key = mykey, source = "osm")
Error in UseMethod("get_heat_map") : 
  no applicable method for 'get_heat_map' applied to an object of class "data.frame"

get_elev_prof(spartans_filt, acts = 3, key = mykey)
Error in UseMethod("get_elev_prof") : 
  no applicable method for 'get_elev_prof' applied to an object of class "data.frame"

#use indexed test data
get_heat_map(spartan_test, acts = 1, key = mykey, source = "osm")
#success
get_elev_prof(spartan_test, acts = 1, key = mykey)
#success


> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.1                         
year           2018                        
month          07                          
day            02                          
svn rev        74947                       
language       R                           
version.string R version 3.5.1 (2018-07-02)
nickname       Feather Spray  

```

**Comment by fawda123** [comment]
Thanks for pointing out this error (and providing a nice reprex).  The dplyr methods that we wrote for the actframe class (`filter` and `mutate`) were not exported to the namespace for rStrava.  It should be working now.  

Note that `subset` will not work because we haven't written a method for the `actframe` class, even though the class label is still retained.  The attributes that are included with the `actframe` objects are dropped with `subset` and the `get_` functions can't find the `unit_vals`.  These should be retained if you use `filter`.

**Comment by lazarus810** [comment]
The issue still persists. If I try to run 1:1 through your given example in README.md for rStrava (1.1.0) the error "no applicable method for 'get_heat_map' applied to an object of class 'data.frame'" still pops up. Thank you for clarification.

**Comment by fawda123** [comment]
I am still unable to reproduce this error.  Just to confirm, the issue using dplyr methods to filter an `actframe` object were addressed in [this commit](https://github.com/fawda123/rStrava/commit/4e9b35b173a874a1f94c9da0d22ecd596c56db34) and should be working.  

As previously noted, the `subset` method will not work and we have no plans of including this functionality.

**Comment by RvdPepper** [comment]
I have the same issue. If I use the code below, I get the following error message: 

_- Error in UseMethod("get_heat_map") : no applicable method for 'get_heat_map' applied to an object of class "data.frame"_

If I use the same code without the filter argument, it works fine.

Any thoughts?

act_data <- compile_activities(my_activities) %>% **filter(start_date >=  '2020-01-01')** 

get_heat_map(act_data, key = google_key(), alpha = NULL, add_elev=FALSE, as_grad = FALSE, col = "darkgreen", size = 2, distlab = F, distval = 0, f = 0.4, expand = 10, maptype = "terrain", source = "google", filltype = "speed")

**Comment by fawda123** [comment]
@RvdPepper I still cannot reproduce the error.  Here's my session info, if that help. 

```
> devtools::session_info()
- Session info -----------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.0 (2020-04-24)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2020-06-08                  

- Packages ---------------------------------------------------------------------------------------------------------------------------------------
 ! package     * version  date       lib source        
   askpass       1.1      2019-01-13 [1] CRAN (R 4.0.0)
   assertthat    0.2.1    2019-03-21 [1] CRAN (R 4.0.0)
   backports     1.1.7    2020-05-13 [1] CRAN (R 4.0.0)
   bitops        1.0-6    2013-08-17 [1] CRAN (R 4.0.0)
   callr         3.4.3    2020-03-28 [1] CRAN (R 4.0.0)
   cli           2.0.2    2020-02-28 [1] CRAN (R 4.0.0)
   colorspace    1.4-1    2019-03-18 [1] CRAN (R 4.0.0)
   crayon        1.3.4    2017-09-16 [1] CRAN (R 4.0.0)
   curl          4.3      2019-12-02 [1] CRAN (R 4.0.0)
   desc          1.2.0    2018-05-01 [1] CRAN (R 4.0.0)
   devtools      2.3.0    2020-04-10 [1] CRAN (R 4.0.0)
   digest        0.6.25   2020-02-23 [1] CRAN (R 4.0.0)
   dplyr       * 1.0.0    2020-05-29 [1] CRAN (R 4.0.0)
   ellipsis      0.3.1    2020-05-15 [1] CRAN (R 4.0.0)
   fansi         0.4.1    2020-01-08 [1] CRAN (R 4.0.0)
   farver        2.0.3    2020-01-16 [1] CRAN (R 4.0.0)
   fastmap       1.0.1    2019-10-08 [1] CRAN (R 4.0.0)
   fs            1.4.1    2020-04-04 [1] CRAN (R 4.0.0)
   generics      0.0.2    2018-11-29 [1] CRAN (R 4.0.0)
   geosphere     1.5-10   2019-05-26 [1] CRAN (R 4.0.0)
   ggmap       * 3.0.0    2019-02-04 [1] CRAN (R 4.0.0)
   ggplot2     * 3.3.1    2020-05-28 [1] CRAN (R 4.0.0)
   ggrepel       0.8.2    2020-03-08 [1] CRAN (R 4.0.0)
   glue          1.4.1    2020-05-13 [1] CRAN (R 4.0.0)
   googleway     2.7.1    2018-09-17 [1] CRAN (R 4.0.0)
   gtable        0.3.0    2019-03-25 [1] CRAN (R 4.0.0)
   htmltools     0.4.0    2019-10-04 [1] CRAN (R 4.0.0)
   htmlwidgets   1.5.1    2019-10-08 [1] CRAN (R 4.0.0)
   httpuv      * 1.5.2    2019-09-11 [1] CRAN (R 4.0.0)
   httr        * 1.4.1    2019-08-05 [1] CRAN (R 4.0.0)
   jpeg          0.1-8.1  2019-10-24 [1] CRAN (R 4.0.0)
   jsonlite      1.6.1    2020-02-02 [1] CRAN (R 4.0.0)
   labeling      0.3      2014-08-23 [1] CRAN (R 4.0.0)
   later         1.0.0    2019-10-04 [1] CRAN (R 4.0.0)
   lattice       0.20-41  2020-04-02 [2] CRAN (R 4.0.0)
   lifecycle     0.2.0    2020-03-06 [1] CRAN (R 4.0.0)
   magrittr      1.5      2014-11-22 [1] CRAN (R 4.0.0)
   mapproj       1.2.7    2020-02-03 [1] CRAN (R 4.0.0)
   maps          3.3.0    2018-04-03 [1] CRAN (R 4.0.0)
   memoise       1.1.0    2017-04-21 [1] CRAN (R 4.0.0)
   mime          0.9      2020-02-04 [1] CRAN (R 4.0.0)
   munsell       0.5.0    2018-06-12 [1] CRAN (R 4.0.0)
   openssl       1.4.1    2019-07-18 [1] CRAN (R 4.0.0)
   packrat       0.5.0    2018-11-14 [1] CRAN (R 4.0.0)
   pillar        1.4.4    2020-05-05 [1] CRAN (R 4.0.0)
   pkgbuild      1.0.8    2020-05-07 [1] CRAN (R 4.0.0)
   pkgconfig     2.0.3    2019-09-22 [1] CRAN (R 4.0.0)
   pkgload       1.1.0    2020-05-29 [1] CRAN (R 4.0.0)
   plyr          1.8.6    2020-03-03 [1] CRAN (R 4.0.0)
   png           0.1-7    2013-12-03 [1] CRAN (R 4.0.0)
   prettyunits   1.1.1    2020-01-24 [1] CRAN (R 4.0.0)
   processx      3.4.2    2020-02-09 [1] CRAN (R 4.0.0)
   promises      1.1.0    2019-10-04 [1] CRAN (R 4.0.0)
   ps            1.3.3    2020-05-08 [1] CRAN (R 4.0.0)
   purrr         0.3.4    2020-04-17 [1] CRAN (R 4.0.0)
   R6            2.4.1    2019-11-12 [1] CRAN (R 4.0.0)
   Rcpp          1.0.4.6  2020-04-09 [1] CRAN (R 4.0.0)
   RCurl         1.98-1.2 2020-04-18 [1] CRAN (R 4.0.0)
   remotes       2.1.1    2020-02-15 [1] CRAN (R 4.0.0)
   RgoogleMaps   1.4.5.3  2020-02-12 [1] CRAN (R 4.0.0)
   rjson         0.2.20   2018-06-08 [1] CRAN (R 4.0.0)
   rlang         0.4.6    2020-05-02 [1] CRAN (R 4.0.0)
   rprojroot     1.3-2    2018-01-03 [1] CRAN (R 4.0.0)
 R rStrava     * 1.1.3    <NA>       [?] <NA>          
   rstudioapi    0.11     2020-02-07 [1] CRAN (R 4.0.0)
   rvest         0.3.5    2019-11-08 [1] CRAN (R 4.0.0)
   scales        1.1.1    2020-05-11 [1] CRAN (R 4.0.0)
   sessioninfo   1.1.1    2018-11-05 [1] CRAN (R 4.0.0)
   shiny         1.4.0.2  2020-03-13 [1] CRAN (R 4.0.0)
   sp            1.4-2    2020-05-20 [1] CRAN (R 4.0.0)
   stringi       1.4.6    2020-02-17 [1] CRAN (R 4.0.0)
   stringr       1.4.0    2019-02-10 [1] CRAN (R 4.0.0)
   testthat      2.3.2    2020-03-02 [1] CRAN (R 4.0.0)
   tibble        3.0.1    2020-04-20 [1] CRAN (R 4.0.0)
   tidyr         1.1.0    2020-05-20 [1] CRAN (R 4.0.0)
   tidyselect    1.1.0    2020-05-11 [1] CRAN (R 4.0.0)
   usethis       1.6.1    2020-04-29 [1] CRAN (R 4.0.0)
   V8            3.1.0    2020-05-29 [1] CRAN (R 4.0.0)
   vctrs         0.3.1    2020-06-05 [1] CRAN (R 4.0.0)
   withr         2.2.0    2020-04-20 [1] CRAN (R 4.0.0)
   XML           3.99-0.3 2020-01-20 [1] CRAN (R 4.0.0)
   xml2          1.3.2    2020-04-23 [1] CRAN (R 4.0.0)
   xtable        1.8-4    2019-04-21 [1] CRAN (R 4.0.0)

[1] C:/Users/mbeck/R/win-library/4.0
[2] C:/Program Files/R/R-4.0.0/library
```

**Comment by RvdPepper** [comment]
First of all, I'm using R version 3.6.1. 
Second: Most of your packages were already installed, only V8, packrat and ggrepel were missing: 
Installing these three missing packages didn't help. 
Updating all my packages also didn't help.

See below my session window (before updating all my packages):

- Session info ---------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Dutch_Netherlands.1252      
 ctype    Dutch_Netherlands.1252      
 tz       Europe/Berlin               
 date     2020-06-08                  

- Packages -------------------------------------------------------------------
 package      * version  date       lib source                           
 animation    * 2.6      2018-12-11 [1] CRAN (R 3.6.3)                   
 askpass        1.1      2019-01-13 [1] CRAN (R 3.6.1)                   
 assertthat     0.2.1    2019-03-21 [1] CRAN (R 3.6.1)                   
 backports      1.1.6    2020-04-05 [1] CRAN (R 3.6.3)                   
 bitops         1.0-6    2013-08-17 [1] CRAN (R 3.6.0)                   
 broom          0.5.2    2019-04-07 [1] CRAN (R 3.6.1)                   
 callr          3.4.3    2020-03-28 [1] CRAN (R 3.6.3)                   
 cellranger     1.1.0    2016-07-27 [1] CRAN (R 3.6.1)                   
 class          7.3-15   2019-01-01 [2] CRAN (R 3.6.1)                   
 classInt       0.4-3    2020-04-07 [1] CRAN (R 3.6.3)                   
 cli            2.0.2    2020-02-28 [1] CRAN (R 3.6.3)                   
 codetools      0.2-16   2018-12-24 [2] CRAN (R 3.6.1)                   
 colorspace     1.4-1    2019-03-18 [1] CRAN (R 3.6.1)                   
 crayon         1.3.4    2017-09-16 [1] CRAN (R 3.6.1)                   
 crosstalk      1.1.0.1  2020-03-13 [1] CRAN (R 3.6.3)                   
 crul           0.9.0    2019-11-06 [1] CRAN (R 3.6.3)                   
 curl           3.3      2019-01-10 [1] CRAN (R 3.6.1)                   
 data.table     1.12.8   2019-12-09 [1] CRAN (R 3.6.3)                   
 DBI            1.0.0    2018-05-02 [1] CRAN (R 3.6.1)                   
 desc           1.2.0    2018-05-01 [1] CRAN (R 3.6.3)                   
 devtools       2.3.0    2020-04-10 [1] CRAN (R 3.6.3)                   
 digest         0.6.25   2020-02-23 [1] CRAN (R 3.6.3)                   
 dplyr        * 0.8.5    2020-03-07 [1] CRAN (R 3.6.3)                   
 dslabs       * 0.7.1    2019-07-14 [1] CRAN (R 3.6.1)                   
 e1071          1.7-3    2019-11-26 [1] CRAN (R 3.6.3)                   
 ellipsis       0.3.0    2019-09-20 [1] CRAN (R 3.6.3)                   
 evaluate       0.14     2019-05-28 [1] CRAN (R 3.6.1)                   
 fansi          0.4.1    2020-01-08 [1] CRAN (R 3.6.3)                   
 farver         2.0.3    2020-01-16 [1] CRAN (R 3.6.3)                   
 fastmap        1.0.1    2019-10-08 [1] CRAN (R 3.6.3)                   
 forcats      * 0.4.0    2019-02-17 [1] CRAN (R 3.6.1)                   
 forecast       8.12     2020-03-31 [1] CRAN (R 3.6.3)                   
 fracdiff       1.5-1    2020-01-24 [1] CRAN (R 3.6.3)                   
 fs             1.3.1    2019-05-06 [1] CRAN (R 3.6.1)                   
 generics       0.0.2    2018-11-29 [1] CRAN (R 3.6.1)                   
 geoaxe         0.1.0    2016-02-19 [1] CRAN (R 3.6.3)                   
 geosphere      1.5-10   2019-05-26 [1] CRAN (R 3.6.3)                   
 gganimate    * 1.0.5    2020-02-09 [1] CRAN (R 3.6.3)                   
 ggforce      * 0.3.1    2019-08-20 [1] CRAN (R 3.6.3)                   
 ggmap        * 3.0.0    2019-02-04 [1] CRAN (R 3.6.3)                   
 ggplot2      * 3.3.0    2020-03-05 [1] CRAN (R 3.6.3)                   
 gifski       * 0.8.6    2018-09-28 [1] CRAN (R 3.6.3)                   
 glue           1.4.0    2020-04-03 [1] CRAN (R 3.6.3)                   
 googleway      2.7.1    2018-09-17 [1] CRAN (R 3.6.3)                   
 gridExtra    * 2.3      2017-09-09 [1] CRAN (R 3.6.3)                   
 gtable         0.3.0    2019-03-25 [1] CRAN (R 3.6.1)                   
 haven          2.1.1    2019-07-04 [1] CRAN (R 3.6.1)                   
 highr          0.8      2019-03-20 [1] CRAN (R 3.6.1)                   
 hms            0.5.0    2019-07-09 [1] CRAN (R 3.6.1)                   
 htmltools      0.4.0    2019-10-04 [1] CRAN (R 3.6.3)                   
 htmlwidgets    1.5.1    2019-10-08 [1] CRAN (R 3.6.3)                   
 httpcode       0.3.0    2020-04-10 [1] CRAN (R 3.6.3)                   
 httpuv         1.5.2    2019-09-11 [1] CRAN (R 3.6.3)                   
 httr         * 1.4.1    2019-08-05 [1] CRAN (R 3.6.3)                   
 imputeTS     * 3.0      2019-07-01 [1] CRAN (R 3.6.3)                   
 jpeg           0.1-8.1  2019-10-24 [1] CRAN (R 3.6.1)                   
 jsonlite       1.6.1    2020-02-02 [1] CRAN (R 3.6.3)                   
 kableExtra   * 1.1.0    2019-03-16 [1] CRAN (R 3.6.3)                   
 KernSmooth     2.23-15  2015-06-29 [2] CRAN (R 3.6.1)                   
 knitr        * 1.23     2019-05-18 [1] CRAN (R 3.6.1)                   
 labeling       0.3      2014-08-23 [1] CRAN (R 3.6.0)                   
 later          1.0.0    2019-10-04 [1] CRAN (R 3.6.3)                   
 lattice        0.20-38  2018-11-04 [2] CRAN (R 3.6.1)                   
 lazyeval       0.2.2    2019-03-15 [1] CRAN (R 3.6.1)                   
 leaflet      * 2.0.3    2019-11-16 [1] CRAN (R 3.6.3)                   
 lifecycle      0.2.0    2020-03-06 [1] CRAN (R 3.6.3)                   
 lmtest         0.9-37   2019-04-30 [1] CRAN (R 3.6.3)                   
 lpSolve        5.6.15   2020-01-24 [1] CRAN (R 3.6.2)                   
 lubridate      1.7.4    2018-04-11 [1] CRAN (R 3.6.1)                   
 magrittr       1.5      2014-11-22 [1] CRAN (R 3.6.1)                   
 mapproj        1.2.7    2020-02-03 [1] CRAN (R 3.6.3)                   
 maps           3.3.0    2018-04-03 [1] CRAN (R 3.6.3)                   
 MASS           7.3-51.4 2019-03-31 [2] CRAN (R 3.6.1)                   
 Matrix         1.2-17   2019-03-22 [2] CRAN (R 3.6.1)                   
 memoise        1.1.0    2017-04-21 [1] CRAN (R 3.6.3)                   
 mgcv           1.8-28   2019-03-21 [2] CRAN (R 3.6.1)                   
 mime           0.7      2019-06-11 [1] CRAN (R 3.6.0)                   
 modelr         0.1.4    2019-02-18 [1] CRAN (R 3.6.1)                   
 munsell        0.5.0    2018-06-12 [1] CRAN (R 3.6.1)                   
 nlme           3.1-140  2019-05-12 [2] CRAN (R 3.6.1)                   
 nnet           7.3-12   2016-02-02 [2] CRAN (R 3.6.1)                   
 oai            0.3.0    2019-09-07 [1] CRAN (R 3.6.3)                   
 openssl        1.4      2019-05-31 [1] CRAN (R 3.6.1)                   
 pillar         1.4.3    2019-12-20 [1] CRAN (R 3.6.3)                   
 pkgbuild       1.0.7    2020-04-25 [1] CRAN (R 3.6.3)                   
 pkgconfig      2.0.3    2019-09-22 [1] CRAN (R 3.6.3)                   
 pkgload        1.0.2    2018-10-29 [1] CRAN (R 3.6.3)                   
 plyr           1.8.6    2020-03-03 [1] CRAN (R 3.6.3)                   
 png            0.1-7    2013-12-03 [1] CRAN (R 3.6.0)                   
 polyclip       1.10-0   2019-03-14 [1] CRAN (R 3.6.0)                   
 prettyunits    1.1.1    2020-01-24 [1] CRAN (R 3.6.3)                   
 processx       3.4.2    2020-02-09 [1] CRAN (R 3.6.3)                   
 progress       1.2.2    2019-05-16 [1] CRAN (R 3.6.1)                   
 promises       1.1.0    2019-10-04 [1] CRAN (R 3.6.3)                   
 ps             1.3.0    2018-12-21 [1] CRAN (R 3.6.1)                   
 purrr        * 0.3.4    2020-04-17 [1] CRAN (R 3.6.3)                   
 quadprog       1.5-8    2019-11-20 [1] CRAN (R 3.6.1)                   
 quantmod       0.4.17   2020-03-31 [1] CRAN (R 3.6.3)                   
 R6             2.4.1    2019-11-12 [1] CRAN (R 3.6.3)                   
 raster         3.1-5    2020-04-19 [1] CRAN (R 3.6.3)                   
 RColorBrewer   1.1-2    2014-12-07 [1] CRAN (R 3.6.0)                   
 Rcpp           1.0.4.6  2020-04-09 [1] CRAN (R 3.6.3)                   
 RcppRoll     * 0.3.0    2018-06-05 [1] CRAN (R 3.6.3)                   
 RCurl          1.98-1.2 2020-04-18 [1] CRAN (R 3.6.3)                   
 readr        * 1.3.1    2018-12-21 [1] CRAN (R 3.6.1)                   
 readxl         1.3.1    2019-03-13 [1] CRAN (R 3.6.1)                   
 remotes        2.1.1    2020-02-15 [1] CRAN (R 3.6.3)                   
 rgbif        * 2.2.0    2020-03-09 [1] CRAN (R 3.6.3)                   
 rgeos          0.5-2    2019-10-03 [1] CRAN (R 3.6.3)                   
 RgoogleMaps    1.4.5.3  2020-02-12 [1] CRAN (R 3.6.3)                   
 rjson        * 0.2.20   2018-06-08 [1] CRAN (R 3.6.0)                   
 rlang          0.4.5    2020-03-01 [1] CRAN (R 3.6.3)                   
 rmarkdown    * 2.1      2020-01-20 [1] CRAN (R 3.6.3)                   
 rprojroot      1.3-2    2018-01-03 [1] CRAN (R 3.6.3)                   
 rStrava      * 1.1.3    2020-05-03 [1] Github (fawda123/rStrava@86e44cd)
 rstudioapi     0.11     2020-02-07 [1] CRAN (R 3.6.3)                   
 rvest          0.3.5    2019-11-08 [1] CRAN (R 3.6.3)                   
 scales         1.1.0    2019-11-18 [1] CRAN (R 3.6.3)                   
 sessioninfo    1.1.1    2018-11-05 [1] CRAN (R 3.6.3)                   
 sf             0.9-3    2020-05-04 [1] CRAN (R 3.6.3)                   
 shiny          1.4.0.2  2020-03-13 [1] CRAN (R 3.6.3)                   
 sp             1.4-1    2020-02-28 [1] CRAN (R 3.6.3)                   
 stinepack      1.4      2018-07-30 [1] CRAN (R 3.6.0)                   
 stringi        1.4.3    2019-03-12 [1] CRAN (R 3.6.0)                   
 stringr      * 1.4.0    2019-02-10 [1] CRAN (R 3.6.1)                   
 testthat       2.3.2    2020-03-02 [1] CRAN (R 3.6.3)                   
 tibble       * 3.0.1    2020-04-20 [1] CRAN (R 3.6.3)                   
 tidyr        * 1.0.2    2020-01-24 [1] CRAN (R 3.6.3)                   
 tidyselect     0.2.5    2018-10-11 [1] CRAN (R 3.6.1)                   
 tidyverse    * 1.2.1    2017-11-14 [1] CRAN (R 3.6.1)                   
 timeDate       3043.102 2018-02-21 [1] CRAN (R 3.6.3)                   
 transformr   * 0.1.1    2018-12-09 [1] CRAN (R 3.6.3)                   
 triebeard      0.3.0    2016-08-04 [1] CRAN (R 3.6.3)                   
 tseries        0.10-47  2019-06-05 [1] CRAN (R 3.6.3)                   
 TTR            0.23-6   2019-12-15 [1] CRAN (R 3.6.3)                   
 tweenr         1.0.1    2018-12-14 [1] CRAN (R 3.6.3)                   
 units          0.6-6    2020-03-16 [1] CRAN (R 3.6.3)                   
 urca           1.3-0    2016-09-06 [1] CRAN (R 3.6.3)                   
 urltools       1.7.3    2019-04-14 [1] CRAN (R 3.6.3)                   
 usethis        1.6.1    2020-04-29 [1] CRAN (R 3.6.3)                   
 vctrs          0.2.4    2020-03-10 [1] CRAN (R 3.6.3)                   
 viridisLite    0.3.0    2018-02-01 [1] CRAN (R 3.6.1)                   
 webshot        0.5.2    2019-11-22 [1] CRAN (R 3.6.3)                   
 whisker        0.3-2    2013-04-28 [1] CRAN (R 3.6.1)                   
 withr          2.2.0    2020-04-20 [1] CRAN (R 3.6.3)                   
 xfun           0.8      2019-06-25 [1] CRAN (R 3.6.1)                   
 XML            3.99-0.3 2020-01-20 [1] CRAN (R 3.6.3)                   
 xml2           1.3.2    2020-04-23 [1] CRAN (R 3.6.3)                   
 xtable         1.8-4    2019-04-21 [1] CRAN (R 3.6.3)                   
 xts            0.12-0   2020-01-19 [1] CRAN (R 3.6.3)                   
 zoo            1.8-8    2020-05-02 [1] CRAN (R 3.6.3)                   

[1] C:/Users/Robert/Documents/R/win-library/3.6
[2] C:/Program Files/R/R-3.6.1/library

**Comment by fawda123** [comment]
Alright, I attempted to run this on R3.6.1 and still am not able to reproduce the error.  What version of dplyr are you using?

**Comment by RvdPepper** [comment]
Hi, I'm using dplyr version 0.8.5

see below details from my session:

dplyr        * 0.8.5    2020-03-07 [1] CRAN (R 3.6.3)

**Comment by RvdPepper** [comment]
Hi, I have updated the dplyr version to 1.0.0 and now it works! Thanks
