### ISSUE TITLE
Error in athl_fun

### ISSUE THREAD

**Issue by pepecebo** [fawda123/rStrava#99]
Hi Marcus,
I am not an expert, so I apologize if my question is too simple or not clear. When I try to get data from an athlete I get an error: 

> athl_fun(2837007, trace = TRUE)
2837007 1 of 1 
Error : SyntaxError: Unexpected end of input
$`2837007`
[1] NA

> athl_fun(2837007, trace = FALSE)
Error : SyntaxError: Unexpected end of input
$`2837007`
[1] NA

The same happens with other athlete IDs.
Thanks

**Comment by fawda123** [comment]
@pepecebo thanks for pointing this out.  It looks like Strava has changed their website backend.  The `notoken` functions will need to be updated and that may take some time.  I suggest you try out the `token` functions instead (https://github.com/fawda123/rStrava#api-functions-token).

**Comment by fawda123** [comment]
@pepecebo this is fixed now, although you can no longer retrieve monthly summary data for the athlete, only the current month. Trophies and followers have also been added.

**Comment by pepecebo** [comment]
Hi @fawda123, I am sorry but I still get the same error. 

> # get athlete data 
> athl_fun(2837007, trace = TRUE)
2837007 1 of 1 
Error : SyntaxError: Unexpected end of input
$`2837007`
[1] NA

And using the token option I also get an error when trying to get my info:

> stoken <- httr::config(token = strava_oauth('Api01', '115455', '198a7306580b63493d7cdbc5e4c6a5a440f2b499', app_scope="activity:read_all"))
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
> myinfo <- get_athlete(stoken, id = '115455')
Error in get_basic(url_athlete(id), stoken) : Forbidden (HTTP 403).

**Comment by fawda123** [comment]
@pepecebo you'll need to install the development version to get the changes.

```
install.packages('rStrava', repos = c('https://fawda123.r-universe.dev', 'https://cloud.r-project.org'))
```

For the token option, looks like you're using your athlete ID for the client ID.  They're different and you should have received the latter when you created the API on the Strava website.  

Also, you should not share your app token information publicy.  I edited your comment to remove the info.

**Comment by pepecebo** [comment]
@fawda123 It works now, Markus, once installed the developer's version. It also works token option. Thanks!

**Comment by pepecebo** [comment]
@fawda123 what I am not sure is if with the token option I can get data from other athletes, or only my own data. Also, can I get activity data since the user started to use Strava? I don't need all the details, but at least basic activity along time. Thanks!

**Comment by fawda123** [comment]
@pepecebo unfortunately you can only retrieve your data with the token functions.  This is a limitation of the Strava API that is beyond my control.  You can get limited data for other users with the notoken functions, but you need to know their athlete id.  

And again, you can retrieve your entire Strava activity record with the token functions, but not others.

**Comment by pepecebo** [comment]
Thanks Markus!

Javier Cebollada
www.javiercebollada.info
Enviado desde un dispositivo móvil - Sent from a handled device.
